name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  buildDotnet:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - run: dotnet build mdDir.sln --no-incremental -c Release
      - run: dotnet publish mdDir.sln -c Release -o ./publish

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUBNAME }}
          password: ${{ secrets.DOCKERHUBPWD }}

      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ptblack/mddir:latest
